### ISSUE TITLE
False positive sun.misc.Unsafe

### ISSUE THREAD

**Issue by 1njected** [nccgroup/VCG#1]
Hi,

When scanning Java code VCG seem to find sun.misc.Unsafe on every code line. Ex:
MEDIUM: Potentially Unsafe Code - sun\.misc\.Unsafe
Line: 22 - C:\Temp\apigw-test\CertifiedClientDetailsServiceImpl.java
This package allows direct access to memory locations, potentially resulting in C-style memory and buffer issues if not used carefully.

MEDIUM: Potentially Unsafe Code - sun\.misc\.Unsafe
Line: 42 - C:\Temp\apigw-test\CertifiedClientDetailsServiceImpl.java
This package allows direct access to memory locations, potentially resulting in C-style memory and buffer issues if not used carefully.

Line 22 contains: package org.apigw.authserver.svc.impl;
Line 42 contains: public class CertifiedClientDetailsServiceImpl implements CertifiedClientDetailsService {

Tried escaping dots (\.) in javafunctions.conf but it didn't work.

**Comment by N1ckDunn** [comment]
Hi Tomas

Thanks for getting in touch. I noticed a variation of this bug for a different code issue. I've tracked down and fixed the bug and will hopefully be releasing a fix via hotel wifi tonight :-)

Thanks
Nick

Sent from my BlackBerry. Please ignore typos and tolerate any brevity and acronyms.

**Comment by 1njected** [comment]
Seems to be working now. Great work! Thanks!

Regards,
Tomas
